# ecolab demo



## Common lazy imports

`lazy_imports` will lazily import all common modules on first usage (`os.path`, `jnp`, `tfds`,...).

All your future colabs can only use a **single** import statement:

In [1]:
from etils.lazy_imports import *

Modules are then dynamically imported on first usage (e.g. `gin`)

In [2]:
assert 'gin' not in sys.modules

gin.clear_config()

List of currently used lazy-imports:

In [3]:
lazy_imports.print_current_imports()

import sys

import gin


View all available imports in the code: https://github.com/google/etils/tree/main/etils/ecolab/lazy_imports.py;l=412

Or in Colab:

In [ ]:
lazy_imports.LAZY_MODULES

Don't hesitate to send a PR if a module is missing!

## Inspect variable interactivelly

`ecolab.inspect` can be used to interactivelly inspect any Python object, recursivelly.

Note: The interactivity require the cell to be executed by the current Kernel.

In [14]:
ecolab.inspect(pathlib.Path.home())

Use `ecolab.auto_inspect()` to automatically add a `INSPECT` button on all cell outputs.

In [15]:
ecolab.auto_inspect()

After executing any cell, you can switch to "inspect" mode by clicking on the button which appear on hover:

In [16]:
{1: 'a', 2: 'b', 3: 'c'}

{1: 'a', 2: 'b', 3: 'c'}

## Auto-plot arrays

Auto-plot array automatically display `tf.Tensor`, `jnp.ndarray`, `np.array`, `torch.Tensor` as image/video.

In [4]:
ecolab.auto_plot_array()

Display big np/tf/jax arrays as image for nicer IPython display


In [5]:
np.random.rand(15, 15, 3)  # (h, w, c)

array([[[0.814617  , 0.44394765, 0.19750801],
        [0.63630891, 0.68616065, 0.7326273 ],
        [0.3677169 , 0.88541623, 0.28364311],
        [0.45772272, 0.45916546, 0.39852536],
        [0.07961772, 0.46626444, 0.46690572],
        [0.46625652, 0.66532721, 0.05763764],
        [0.52527239, 0.48235259, 0.13148244],
        [0.82034923, 0.71137973, 0.8298467 ],
        [0.36681357, 0.23431422, 0.57780795],
        [0.43293635, 0.27802563, 0.30661722],
        [0.38811695, 0.46762499, 0.26540326],
        [0.72561743, 0.95978842, 0.07654032],
        [0.10095081, 0.5337542 , 0.99661087],
        [0.78251009, 0.60259144, 0.82618538],
        [0.67610295, 0.38383464, 0.8675047 ]],

       [[0.96570433, 0.97753347, 0.01319   ],
        [0.81891337, 0.61397015, 0.7759996 ],
        [0.81719032, 0.83142752, 0.44131399],
        [0.37554095, 0.25664966, 0.49843652],
        [0.58084864, 0.1606051 , 0.90050652],
        [0.98250461, 0.25290553, 0.0029109 ],
        [0.59695903, 0.39905091, 0.36230979],
        [0.04432277, 0.52615782, 0.12045897],
        [0.13727482, 0.79842987, 0.31662279],
        [0.9080664 , 0.86999085, 0.35349585],
        [0.93332832, 0.23275916, 0.21967762],
        [0.97886858, 0.14048684, 0.55151841],
        [0.50108431, 0.85572195, 0.8461618 ],
        [0.49618285, 0.72191389, 0.34532157],
        [0.15397287, 0.07839849, 0.71364169]],

       [[0.95152054, 0.49148956, 0.69822022],
        [0.90314829, 0.97403224, 0.16127532],
        [0.32865013, 0.40660102, 0.4731603 ],
        [0.27094559, 0.6604646 , 0.71281109],
        [0.2869501 , 0.03866977, 0.4971068 ],
        [0.80995478, 0.69223104, 0.95441386],
        [0.41316367, 0.19913088, 0.00742155],
        [0.15314405, 0.25438241, 0.55449246],
        [0.22843023, 0.22383498, 0.75733271],
        [0.61466085, 0.31172478, 0.15733595],
        [0.59439188, 0.23488488, 0.01864352],
        [0.90402321, 0.97592068, 0.1395122 ],
        [0.30808716, 0.75493568, 0.26946497],
        [0.24656795, 0.54556975, 0.21053353],
        [0.63314096, 0.05836904, 0.85213547]],

       [[0.78845403, 0.22182715, 0.0980087 ],
        [0.70543977, 0.8304115 , 0.30422196],
        [0.98293592, 0.83027191, 0.08325281],
        [0.49706988, 0.91157486, 0.0225703 ],
        [0.379653  , 0.58234146, 0.19256069],
        [0.99466723, 0.13158966, 0.4954198 ],
        [0.91702523, 0.5921761 , 0.09630995],
        [0.99977678, 0.45589817, 0.24584723],
        [0.42634311, 0.33248819, 0.47582783],
        [0.06521541, 0.75317942, 0.05019955],
        [0.99684934, 0.80279333, 0.71883549],
        [0.14002247, 0.39287056, 0.09596116],
        [0.17603472, 0.98830856, 0.50560935],
        [0.65379999, 0.71325428, 0.63768298],
        [0.96428712, 0.30246775, 0.01783128]],

       [[0.90322601, 0.76275549, 0.41550371],
        [0.04606797, 0.3213878 , 0.20339533],
        [0.14318024, 0.42917036, 0.71927086],
        [0.54923173, 0.40310073, 0.19178315],
        [0.40349278, 0.14612028, 0.72917925],
        [0.22779065, 0.75369922, 0.52218635],
        [0.63385842, 0.33791972, 0.00449747],
        [0.14227189, 0.92142637, 0.86178702],
        [0.92430482, 0.42548061, 0.66724294],
        [0.07385894, 0.16727981, 0.23931718],
        [0.63301219, 0.50778605, 0.40621703],
        [0.19609554, 0.35413326, 0.33001313],
        [0.15398662, 0.91000393, 0.69769195],
        [0.03650042, 0.02522674, 0.39871999],
        [0.28207516, 0.35738003, 0.15758513]],

       [[0.61352741, 0.99803712, 0.42184638],
        [0.57808309, 0.95880855, 0.85084165],
        [0.85889873, 0.03262288, 0.81334587],
        [0.9756788 , 0.80059224, 0.9446802 ],
        [0.74951814, 0.43623018, 0.11114686],
        [0.17820438, 0.98597657, 0.24363542],
        [0.18267329, 0.93451723, 0.34741162],
        [0.81637671, 0.40578347, 0.6428514 ],
        [0.6722272 , 0.22843128, 0.0376904 ],
        [0.12292952, 0.30077106, 0.69819675],
        [0.12390362, 0.28688475, 0.62859893],
        [0.19851587, 0.05239608, 0

In [6]:
np.random.rand(4, 15, 15, 3)  # (n, h, w, c)

array([[[[0.05176385, 0.97727647, 0.4210093 ],
         [0.08471593, 0.7252697 , 0.45992998],
         [0.66798923, 0.19738138, 0.4952952 ],
         ...,
         [0.14524648, 0.1633938 , 0.40370329],
         [0.93821602, 0.0296198 , 0.58361065],
         [0.21260674, 0.57188768, 0.03135199]],

        [[0.85876904, 0.03496457, 0.85764102],
         [0.70967379, 0.19005151, 0.69614684],
         [0.31034347, 0.40399027, 0.43458647],
         ...,
         [0.98232762, 0.51938034, 0.20399037],
         [0.65390734, 0.27702747, 0.45181695],
         [0.24439492, 0.69794221, 0.12821834]],

        [[0.05109475, 0.29228068, 0.47531684],
         [0.75930619, 0.80897707, 0.16356057],
         [0.38711621, 0.47931747, 0.26017161],
         ...,
         [0.68169061, 0.88021607, 0.30993762],
         [0.95061455, 0.84342872, 0.67881742],
         [0.93598665, 0.86336415, 0.33820633]],

        ...,

        [[0.52350178, 0.96007053, 0.37697031],
         [0.41425703, 0.36743838, 0.76350523],
         [0.13649321, 0.46431631, 0.83988806],
         ...,
         [0.73403855, 0.97894925, 0.52490009],
         [0.90551365, 0.96554329, 0.78828617],
         [0.1757843 , 0.8657418 , 0.31911003]],

        [[0.07936475, 0.27158843, 0.79617979],
         [0.08354113, 0.77794628, 0.70435152],
         [0.31496578, 0.7319724 , 0.81393245],
         ...,
         [0.31524013, 0.27911316, 0.11203789],
         [0.63866577, 0.57221489, 0.72923686],
         [0.78078937, 0.13178924, 0.572845  ]],

        [[0.22633696, 0.04303948, 0.15786061],
         [0.86304343, 0.99760706, 0.79110367],
         [0.50876024, 0.74538291, 0.35470579],
         ...,
         [0.60631642, 0.62756205, 0.09005042],
         [0.56420697, 0.49136856, 0.13625065],
         [0.14148909, 0.71456247, 0.67595484]]],


       [[[0.57986447, 0.3850966 , 0.47225635],
         [0.60296593, 0.20202154, 0.42710839],
         [0.77900398, 0.97349057, 0.25160355],
         ...,
         [0.12297189, 0.72117762, 0.92764294],
         [0.38497252, 0.53365382, 0.00537394],
         [0.20037661, 0.29399286, 0.99671105]],

        [[0.68791973, 0.12117374, 0.0740101 ],
         [0.81820307, 0.84896287, 0.64340037],
         [0.14344704, 0.03000144, 0.39998974],
         ...,
         [0.36961953, 0.04337411, 0.13536788],
         [0.2518528 , 0.75930017, 0.22819698],
         [0.6015509 , 0.35376165, 0.83895598]],

        [[0.46258093, 0.09716649, 0.92809107],
         [0.75287175, 0.60205471, 0.79976332],
         [0.42216198, 0.90027476, 0.34100559],
         ...,
         [0.19501356, 0.61944637, 0.15184706],
         [0.1174771 , 0.5497984 , 0.65391461],
         [0.22363877, 0.95447581, 0.79316158]],

        ...,

        [[0.98929735, 0.13234219, 0.97607802],
         [0.01513456, 0.23978804, 0.80176705],
         [0.39320944, 0.65615114, 0.88813411],
         ...,
         [0.46123466, 0.7868057 , 0.38489128],
         [0.97303236, 0.45217972, 0.11773293],
         [0.47755526, 0.16606471, 0.79702268]],

        [[0.76321752, 0.5780768 , 0.39299448],
         [0.74845448, 0.044137  , 0.5085054 ],
         [0.94104083, 0.97190903, 0.15318108],
         ...,
         [0.72526804, 0.39018726, 0.11056839],
         [0.48973433, 0.00217134, 0.40544744],
         [0.65569025, 0.79471324, 0.64902798]],

        [[0.91218981, 0.94364587, 0.42933314],
         [0.62098102, 0.39215927, 0.08758741],
         [0.22339053, 0.30654416, 0.25867297],
         ...,
         [0.16696744, 0.29434863, 0.60701494],
         [0.78647487, 0.07664803, 0.65971986],
         [0.38638179, 0.77485189, 0.09891617]]],


       [[[0.58360273, 0.13675609, 0.02617359],
         [0.09485374, 0.53597313, 0.66385963],
         [0.71693225, 0.09421395, 0.32207123],
         ...,
         [0.42369748, 0.12673226, 0.69801418],
         [0.57848331, 0.69931646, 0.271345  ],
         [0.24911692, 0.74004255, 0.49118898]],

        [[0.06710748, 0.53251342, 0.90882772],
         [0.26756516, 0.96771696, 0.16167524],


When `n >= 15`, the images are displayed as video. `15` is customisable in `ecolab.auto_plot_array(video_min_num_frames=1)`.

In [7]:
np.random.rand(20, 100, 100, 3)  # (n, h, w, c)

array([[[[6.95348524e-01, 5.60829014e-01, 7.68155703e-01],
         [9.33451896e-01, 1.96864871e-01, 2.17305933e-01],
         [8.90615980e-01, 2.46692274e-01, 3.25213039e-01],
         ...,
         [1.87010317e-01, 1.11416821e-01, 5.83498098e-01],
         [5.93994677e-01, 3.45334358e-01, 2.72374933e-01],
         [3.12279641e-01, 4.43834313e-01, 1.44155455e-02]],

        [[1.46239617e-01, 6.33054761e-01, 1.78859573e-01],
         [2.44125098e-01, 5.83106199e-01, 8.56453003e-01],
         [7.89495769e-01, 9.52074493e-01, 8.38135478e-01],
         ...,
         [9.21105264e-01, 5.75941798e-01, 3.91698365e-01],
         [6.29388814e-01, 3.48352333e-01, 5.44455236e-01],
         [1.55447136e-01, 4.98361588e-01, 7.92347065e-02]],

        [[7.13191351e-01, 1.59797166e-02, 9.17918116e-01],
         [1.20410853e-01, 6.56834610e-01, 6.61539641e-01],
         [8.63820191e-01, 9.56059589e-01, 5.17240622e-01],
         ...,
         [8.22373421e-01, 4.49298156e-01, 6.85357750e-01],
         [9.47901443e-01, 6.52553950e-01, 3.25345853e-01],
         [6.13006778e-01, 2.87004573e-01, 7.02785260e-01]],

        ...,

        [[8.38419904e-01, 5.34194908e-01, 7.44468299e-01],
         [4.10441997e-01, 6.70195449e-01, 6.54401153e-01],
         [7.23469397e-01, 9.81453765e-01, 6.29536260e-01],
         ...,
         [3.46835496e-02, 2.65742709e-01, 2.86098808e-01],
         [7.08742791e-01, 3.85301193e-01, 5.72166046e-02],
         [2.81360190e-01, 5.62020678e-01, 2.64264259e-02]],

        [[6.61987070e-02, 9.54466212e-01, 7.85866023e-01],
         [6.17791522e-01, 3.84124986e-01, 8.72169926e-01],
         [1.33106117e-01, 3.57876915e-01, 5.54406487e-01],
         ...,
         [7.92308283e-01, 2.91872858e-01, 3.84894357e-01],
         [1.85412111e-01, 8.25386514e-01, 2.90862770e-01],
         [5.73732732e-01, 7.20556551e-01, 6.19269480e-01]],

        [[6.12932234e-01, 5.21728224e-01, 9.82546982e-01],
         [9.86820392e-02, 5.71413581e-01, 5.27908135e-01],
         [5.59232606e-01, 5.84965206e-02, 6.01293024e-01],
         ...,
         [2.86611537e-01, 3.90547213e-01, 9.96559299e-01],
         [4.04717962e-01, 4.17663521e-01, 4.98516457e-01],
         [7.60407355e-01, 3.58939416e-01, 1.47442566e-01]]],


       [[[7.85614814e-02, 9.32332598e-01, 8.96107718e-01],
         [8.98360738e-01, 5.78006930e-01, 1.34472741e-01],
         [1.86732651e-01, 7.78464492e-01, 2.70481880e-01],
         ...,
         [2.77745592e-02, 6.62224020e-02, 3.10028759e-02],
         [8.92858491e-01, 9.84720626e-01, 3.61215061e-01],
         [2.87381671e-01, 7.70224163e-01, 7.86237049e-01]],

        [[9.45295747e-01, 5.16443902e-01, 3.41633006e-01],
         [6.85028027e-01, 7.56157479e-01, 7.39615900e-01],
         [1.11365546e-02, 2.50260024e-01, 4.46981476e-01],
         ...,
         [5.59796527e-01, 6.47522288e-01, 2.88151745e-01],
         [6.85936567e-01, 1.49440601e-01, 1.51809061e-01],
         [5.90175796e-01, 8.54772562e-01, 8.11745179e-01]],

        [[2.34930809e-01, 3.76421609e-01, 4.98166081e-01],
         [7.32024202e-01, 4.35984221e-01, 4.83606707e-01],
         [9.34355057e-01, 8.11996691e-01, 2.24887283e-01],
         ...,
         [9.61191336e-01, 3.99347936e-01, 2.18991655e-01],
         [1.41059993e-01, 2.90838559e-02, 2.21691535e-01],
         [8.47821058e-01, 8.93320450e-01, 4.05596500e-01]],

        ...,

        [[9.78384474e-01, 4.03808099e-01, 3.06664250e-01],
         [7.52129921e-01, 5.43621592e-02, 1.82775305e-01],
         [2.82967377e-01, 1.68219386e-01, 6.12955247e-01],
         ...,
         [5.05456815e-02, 1.62042656e-01, 1.57804482e-01],
         [4.06377154e-01, 5.89669189e-01, 8.44238424e-01],
         [4.90521861e-01, 6.26137647e-01, 4.53338266e-01]],

        [[8.04661396e-01, 2.74041671e-01, 1.81739039e-01],
         [2.79659824e-01, 3.34098581e-01, 8.87637175e-01],
         [7.57201488e-01, 1.14977963e-01, 6.53332485e-01],
         ...,
         [7.77890223e-01, 7.31159990e-01, 1.25872851e-01],
         [7.33364484

In [8]:
np.random.rand(1, 4, 3)  # Small arrays with (h, w) < (10, 10) displayed as text

array([[[0.17776493, 0.74036457, 0.21391334],
        [0.0542936 , 0.82747557, 0.51429675],
        [0.12432858, 0.17803704, 0.5047246 ],
        [0.17052411, 0.53610385, 0.03514284]]])

## Interactive display

When displaying a lot of text (e.g. a config file content), it can be helpful to wrap it inside a collapsible section.

In [ ]:
with ecolab.collapse('Content:'):
  for _ in range(20):
    print('This text will be collapsed...')

Inspecting a nested Json dict/list interactivelly:

Supports filtering (e.g. try regex `x.[0-9]` bellow)

In [9]:
ecolab.json({'a': [1, 2, 3], 'b': True, 'c': {'x': [{}, {'a': 123}], 'y': None}})

## Bi-directional Python/Javascript communications

Ecolab provide a simplified API for Python<>Js communication which works for
both `colab` and `jupyter` notebooks.

Use `ecolab.register_js_fn` to register any Python functions.

In [12]:
@ecolab.register_js_fn
def my_fn(x, y, z):
  print(f'Called with {x}, {y}, {z}')
  return {'sum': x + y + z}

The function can then be called from Javascript with `call_python('<fn_name>', [arg0, ...], {kwarg0: ..., kwarg1: ...})`

In [13]:
# Currently has to be executed in the same cell to install the library
IPython.display.display(IPython.display.HTML(ecolab.pyjs_import()))

IPython.display.HTML("""
<div id="my_output"></div>
<script>
  async function main() {
    // my_fn(1, 2, z=3)  == {'sum': 6}
    out = await call_python('my_fn', [1, 2], {z: 3});

    const elem = document.getElementById('my_output');
    elem.innerHTML = `Output is ${out["sum"]}`;
  }
  main();
</script>
""")

Called with 1, 2, 3
